# Generated by Django 4.2.1 on 2023-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ListNFService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contratos", models.IntegerField()),
                ("codigo", models.IntegerField()),
                ("cnpj_cpf", models.CharField(max_length=14)),
                ("grupo", models.CharField(max_length=50)),
                ("razao_social", models.CharField(max_length=120)),
                ("regime_tributario", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("vencimento", models.DateField()),
                ("pis", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cofins", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ir", models.DecimalField(decimal_places=2, max_digits=10)),
                ("csll", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inss", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valor_liquido", models.DecimalField(decimal_places=2, max_digits=10)),
                ("email", models.EmailField(max_length=254)),
                ("corpo_nota", models.CharField(default="semTexto", max_length=50)),
            ],
        ),
    ]
