# Generated by Django 4.2.1 on 2023-07-05 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("appListNf", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listnfservice",
            old_name="cnpj_cpf",
            new_name="cnpj",
        ),
    ]
