# Generated by Django 4.2.1 on 2023-07-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appListNf", "0002_rename_cnpj_cpf_listnfservice_cnpj"),
    ]

    operations = [
        migrations.AddField(
            model_name="listnfservice",
            name="checkNf",
            field=models.BooleanField(default=False),
        ),
    ]
