# Generated by Django 4.2.1 on 2023-07-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appListNf", "0003_listnfservice_checknf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listnfservice",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="email",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="grupo",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="regime_tributario",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="status",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="vencimento",
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="valor_bruto",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
