# Generated by Django 4.2.1 on 2023-07-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appListNf", "0004_remove_listnfservice_codigo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listnfservice",
            name="Numero_NF",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
