# Generated by Django 4.2.1 on 2023-08-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appListNf", "0005_listnfservice_numero_nf"),
    ]

    operations = [
        migrations.AddField(
            model_name="listnfservice",
            name="pasta",
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
