# Generated by Django 4.2.1 on 2023-10-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appListNf", "0006_listnfservice_pasta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listnfservice",
            name="Numero_NF",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="cnpj",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="cofins",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="contratos",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="corpo_nota",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="csll",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="inss",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="ir",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="pis",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="razao_social",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="valor_bruto",
        ),
        migrations.RemoveField(
            model_name="listnfservice",
            name="valor_liquido",
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="atividade_economica",
            field=models.CharField(default="semTexto", max_length=120),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="bairro",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="cep",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="cnpj_cpf",
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="cod_mun_prestador",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="cod_mun_tomador",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="complemento",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="discrimicacao",
            field=models.CharField(default="semTexto", max_length=120),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="empresa",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="endereco",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="n_cnpj_cpf",
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="nome",
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="listnfservice",
            name="numero",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
