# Generated by Django 4.2.1 on 2023-10-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appListNf", "0009_listnfservice_valor_alter_listnfservice_cep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listnfservice",
            name="link_nfse",
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
    ]
